### ISSUE TITLE
Consommation année non complete

### ISSUE THREAD

**Issue by FeelDomotique69** [jeedom/plugin-wescontrol#1]
Hello , la consommation année de la TIC1 dans le plugin wescontrol est la conso HP annuelle il manque le rajout HC.
Mais cela aussi serait intéressant d'avoir le report des 2 et du total idem pour le cout.
Bravo pour ce super boulot
Philippe

**Comment by FeelDomotique69** [comment]
![Capture](https://user-images.githubusercontent.com/79406562/118131066-5986be80-b3fe-11eb-86b8-df7a9b74a9ff.JPG)

example

**Comment by Salvialf** [comment]
Bonjour,

Le plugin ne fait que récupérer les valeurs transmises par le Wes, il faudrait donc qu'il y ait un décalage entre la valeur dans Jeedom et celle dans le Wes pour qu'il manque quoi que ce soit. Or à première vue les données correspondent : 
![image](https://user-images.githubusercontent.com/48010158/118239679-61943c00-b49a-11eb-8a48-fbd2e23ac3e3.png)
![image](https://user-images.githubusercontent.com/48010158/118239704-6b1da400-b49a-11eb-82bc-e580bb783849.png)

Cordialement,

**Comment by FeelDomotique69** [comment]
Bonjour Salvialf

Déjà merci pour tout ce que vous faites pour Jeedom depuis longtemps ( 
ainsi que les autres contributeurs).

Concernant ce petit soucis de mise en forme je pense n 'avoir pas été 
assez explicite.

Voici des détails;

copies écran au mème moment


Donc la consommation année du widget n 'est que la consommation HP

L 'deal serait d 'avoir HP HC et le total

Je me doute que vous dépendez de Cartelectronic et du Data.cgx donc peut 
être pas si simple.

C'est donc une simple remontée pour participer un petit peu :-) car il 
est difficile de pouvoir tester toutes les configurations


bien cordialement


Philippe


Le 14/05/2021 à 09:55, Salvialf a écrit :

**Comment by Salvialf** [comment]
Ah oui je m'étais focalisé sur le coût que correspond bien au total mais la consommation année ne remonte que les heures pleines effectivement.

Merci pour la remontée ce sera pris en compte dans la prochaine beta.

**Comment by Salvialf** [comment]
Pour information il s'agit d'un bug identifié par l'équipe carteletronic qui sera corrigée lors d'une prochaine mise à jour du serveur Wes: https://www.cartelectronic.fr/blog/?topic=at1-d
