### ISSUE TITLE
erreur history a 5.00 h 

### ISSUE THREAD

**Issue by FeelDomotique69** [jeedom/plugin-wescontrol#2]
hello 
ce matin ce message d'erreur

Erreur l'archivage des historiques : {"cmd_id":"632","archivePackage":3600,"archiveTime":"2021-05-12 03:00:04"} => [MySQL] Error code : 22003 (1264). Out of range value for column '(null)' at row 1 : REPLACE INTO historyArch(cmd_id,`datetime`,value) SELECT cmd_id,MIN(`datetime`),avg(CAST(value AS DECIMAL(12,2))) as value FROM history WHERE `datetime`	

concerne le cout par jour 

merci d 'avoir repris ce plugin  !    tres utile ce WES quand ca marche

cordialement

Philippe

**Comment by Salvialf** [comment]
Bonjour,

Il semble qu'une ou plusieurs valeurs vides aient été enregistrées en historique de la commande portant l'id 632. Il faut soit identifier les valeurs erronées et les supprimer de l'historique soit décocher l'historisation de la commande, sauvegarder l'équipement et historiser à nouveau la commande néanmoins les précédents historiques seront perdus.

Un contrôle sera ajouté à ce niveau lors de la prochaine version beta.

Cordialement,
