### ISSUE TITLE
Bug affichage wifget relais par exemple

### ISSUE THREAD

**Issue by FeelDomotique69** [jeedom/plugin-wescontrol#3]
Hello 

Si on valide l'affichage de l'etat et son history on a 2 fois l'affichage " etat" par défaut.

![Capture](https://user-images.githubusercontent.com/79406562/118130750-06ad0700-b3fe-11eb-8e96-f18b4982ce64.JPG)

merci et bon courage c 'est un gros morceau  :-)

Philippe

**Comment by Salvialf** [comment]
Bonjour,

Il s'agit de l'usage normal de Jeedom. Les 2 commandes action pilotent et reflètent l'état de l'équipement. la commande Etat est volontairement non affichée tel qu'indiqué [dans la documentation Jeedom](https://doc.jeedom.com/fr_FR/core/4.1/widgets#Toggle%20d%E2%80%99ic%C3%B4ne%20ON%2FOFF) : 
> Conseil
> Décocher la case “Afficher” de la commande info/binaire qui n’aura pas besoin d’être affichée.

Si la commande info doit être affichée afin d'accéder à l'historique par exemple, il suffit de revenir au widget par défaut sur les 2 commandes action.

Cordialement,
